### ISSUE TITLE
Make a Concourse resource 

### ISSUE THREAD

**Issue by petewall** [vmware-labs/marketplace-cli#13]
A Concourse resource would be very helpful in building pipelines that utilize Marketplace products.

A basic framework for how the resource could look would be:

```yaml
---
resource_types:
- name: marketplace-product
  type: registry-image
  source:
    repository: TBD/marketplace-product-resource
    tag: bestest

resources:
  - name: my-product
    type: marketplace-product
    icon: storefront
    source:
      marketplace_host: stg.market.csp.vmware.com
      csp_api_key: ((csp_api_key))
      product_slug: test-ova-product-31
      version_ordering: semver

jobs:
  - name: test-product
    plan:
      - get: my-product
      - task: run-tests
        ...
```

## Source
Defines the product under question, connection information, authentication information
Version ordering could be:
* default - however marketplace returns
* semver - order the products on semver rules, will break if the product does not follow semver rules
* lexical - order alphanumerically
version_regex: Could be used to match only specific versions of the product (e.g. `1.2.*`)

## Check
Gets the list of versions for the given product

## In
Download the product and store information into a few files:
product.json - raw product information

if the product is not a listing:
version - version of the product downloaded
type - type of content attached to this product ("OVA", "HELM", "CONTAINER")

<filename> - The content of the product attached.

Parameters
skip_download: Optional. Default false. Skip downloading any attached content. Useful only to trigger a job without using product content.

## Out
TBD. No-op at this point
